# Generated by Django 3.2.7 on 2021-09-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_credit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='CREATED', max_length=16),
        ),
    ]
